export const SAVE_PRODUCTS_TO_STORE = "SAVE_PRODUCTS_TO_STORE";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CHOSEN_CATEGORY = "SET_CHOSEN_CATEGORY";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_USERS = "SET_USERS";
